[build]
  publish   = "dist"               # byt till din Bolt-publiceringsmapp
  functions = "netlify/functions"  # pekar på dina serverless functions

[dev]
  command = "npm start"            # hur du kör Bolt lokalt om du använder Netlify CLI
  port    = 8888
